title: MIGA Improvement Proposals (MIPs)
description: Governance proposals for the MIGA Civic OS ecosystem
url: "https://pips.miga.us.org"
baseurl: ""

# Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Include markdown files
include:
  - PIPs
  - README.md
  - CNAME

# Exclude unnecessary files
exclude:
  - .github/
  - LICENSE
  - "*.log"
